version: "3.7"	

services:	
  tosios:	
    image: halftheopposite/tosios	
    container_name: tosios	
    restart: always	
    ports:	
      - 3001:3001
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
